In [2]:
import numpy as np

In [3]:
#输入数据
X = np.array([[1,0,0],
              [1,0,1],
              [1,1,0],
              [1,1,1]])
#标签
Y = np.array([[0,1,1,0]])
#权值初始化，取值范围-1到1
V = np.random.random((3,4))*2-1 
W = np.random.random((4,1))*2-1
print(V)
print(W)
#学习率设置
lr = 0.11

def sigmoid(x):
    return 1/(1+np.exp(-x))

def dsigmoid(x):  #sigmoid的导数
    return x*(1-x)

def update():
    global X,Y,W,V,lr
    
    L1 = sigmoid(np.dot(X,V))#隐藏层输出(4,4)
    L2 = sigmoid(np.dot(L1,W))#输出层输出(4,1)
    
    L2_delta = (Y.T - L2)*dsigmoid(L2)
    L1_delta = L2_delta.dot(W.T)*dsigmoid(L1)
    
    W_C = lr*L1.T.dot(L2_delta)
    V_C = lr*X.T.dot(L1_delta)
    
    W = W + W_C
    V = V + V_C

[[-0.76946188 -0.60027638 -0.85392394  0.78617289]
 [-0.24246373 -0.79898804  0.29203499  0.04062343]
 [ 0.13434092 -0.5335259   0.63164351 -0.11606211]]
[[ 0.24996041]
 [ 0.65710266]
 [-0.38480584]
 [ 0.310705  ]]


In [3]:
for i in range(20000):
    update()#更新权值
    if i%500==0:
        L1 = sigmoid(np.dot(X,V))#隐藏层输出(4,4)
        L2 = sigmoid(np.dot(L1,W))#输出层输出(4,1)
        print('Error:',np.mean(np.abs(Y.T-L2)))
        
L1 = sigmoid(np.dot(X,V))#隐藏层输出(4,4)
L2 = sigmoid(np.dot(L1,W))#输出层输出(4,1)
print(L2)

def judge(x):
    if x>=0.5:
        return 1
    else:
        return 0

for i in map(judge,L2):
    print(i)

Error: 0.5007788048690339
Error: 0.49875853883814386
Error: 0.4959785606521968
Error: 0.48433843248431974
Error: 0.4492355673477073
Error: 0.38874536478565347
Error: 0.3219063981489949
Error: 0.26493091517435
Error: 0.19803373884267123
Error: 0.14462215274169007
Error: 0.11522451370255066
Error: 0.0967435858838225
Error: 0.08413762094765458
Error: 0.07498101634728468
Error: 0.06800776252252429
Error: 0.0625021252908765
Error: 0.058031111111931655
Error: 0.05431784023327238
Error: 0.051177034833616554
Error: 0.0484799674952935
Error: 0.04613434289973458
Error: 0.044072199433596776
Error: 0.04224233774140732
Error: 0.04060541674493422
Error: 0.03913068115727075
Error: 0.03779371991004895
Error: 0.03657489494153775
Error: 0.03545821710366708
Error: 0.03443052711567095
Error: 0.033480888900816005
Error: 0.03260013351909562
Error: 0.03178051166656294
Error: 0.03101542562927437
Error: 0.030299220191411576
Error: 0.029627017841581046
Error: 0.028994587653118433
Error: 0.02839824003778333
Erro